version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: mycustomuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: deneme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mycustomuser -d deneme"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    image: denizcex/javanewsrss:0.0.1
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/deneme
      SPRING_DATASOURCE_USERNAME: mycustomuser
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: denizcex/frontend:0.0.1
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres



volumes:
  postgres_data:


