name: newsflow

services:
  postgres:
    image: postgres:18.3-alpine3.22
    container_name: newsflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: mycustomuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: deneme
    ports:
      - "5432:5432"
    volumes:
      - postgres18_cluster_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mycustomuser -d deneme"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: newsflow-backend:local
    container_name: newsflow-backend
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/deneme
      SPRING_DATASOURCE_USERNAME: mycustomuser
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    image: newsflow-frontend:local
    container_name: newsflow-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: newsflow-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres18_cluster_data:
